# Learning Python with Vincent
## And many other things to come yet ;-)

*Date: Sat Sep 10 13:16:48 IST 2016*

<hr>

## Exercise-1: Simple Sorting

The logic is this.

- Take a few numbers from the user.
- Put them in a list.
- Sort them without using builtin methods like 'sort' and all, that is, put them in ascending order.

In [1]:
list = []

In [2]:
for i in range(5):
    list.append(input("Enter a number: "))

Enter a number: 10
Enter a number: 20
Enter a number: 15
Enter a number: 12
Enter a number: 5


In [3]:
list

[10, 20, 15, 12, 5]

In [4]:
for number in list:
    print number

10
20
15
12
5


In [15]:
for number in list:
    for i in list:
        if list[i] > list[i+1]:
            i = i+1
            print number, list[i]

TypeError: 'type' object is not iterable

In [22]:
list[0] > list[1]

False

In [19]:
for i in list:
    list[i] > list[i+1]

IndexError: list index out of range

### After first explanation of logic

In [6]:
for i in enumerate(list):
    # use insert() command
    if list[i+1] > list[i]:
        list.insert(i, list.pop(i+1))

TypeError: 'type' object is not iterable

In [7]:
# Checking if enumerate can be used with an example:
ints = [8, 23, 45, 12, 78]
for index, value in enumerate(ints):
    print index, value

0 8
1 23
2 45
3 12
4 78


Nope! `enumerate` cannot be used. 

In [8]:
# One more reference from other sources:
data_list = [-5, -23, 5, 0, 23, -6, 23, 67]
new_list = []

while data_list:
    minimum = data_list[0]  # arbitrary number in list 
    for x in data_list: 
        if x < minimum:
            minimum = x
    new_list.append(minimum)
    data_list.remove(minimum)    

print new_list

[-23, -6, -5, 0, 5, 23, 23, 67]


In [15]:
# Therefore, the final solution is:
list = []
for i in range(5):
    list.append(input("Enter a number: "))

new_list = []

while list:
    temp = list[0]  # arbitrary number in list 
    for x in list: 
        if x < temp:
            temp = x
    new_list.append(temp)
    list.remove(temp)    

print list
print new_list

Enter a number: 10
Enter a number: 20
Enter a number: 15
Enter a number: 12
Enter a number: 5
[]
[5, 10, 12, 15, 20]


But the above solution is emptying my list. If it is not emptied, the loop gets to infinity. Although not so technical and sophisticated, the only thing I can do for now is to create another list with the same elements.

In [25]:
# THE END
list = []
for i in range(5):
    list.append(input("Enter a number: "))

old_list = list
print "The Unsorted List elements are: ", old_list
new_list = []

while list:
    temp = list[0]  # arbitrary number in list 
    for x in list: 
        if x < temp:
            temp = x
    new_list.append(temp)
    list.remove(temp)    

print "The Sorted List elements are: ", new_list

Enter a number: 10
Enter a number: 20
Enter a number: 15
Enter a number: 12
Enter a number: 5
The Unsorted List elements are:  [10, 20, 15, 12, 5]
The Sorted List elements are:  [5, 10, 12, 15, 20]


In [32]:
# Another way od doing the same found online
a = [3, 1, 5, 2, 4]

for i in a[1:]:
    j = a.index(i)
    while j > 0 and a[j-1] > a[j]:
        a[j], a[j-1] = a[j-1], a[j]
        j = j - 1
print a

[1, 2, 3, 4, 5]


Both the solutions are found in [this link](http://stackoverflow.com/questions/11964450/python-order-a-list-of-numbers-without-built-in-sort-min-max-function). Finally, the point I should keep in mind is, I couldn't do it on my own. But I certainly understood what these codes mean, though. Not happy! :-(

## Exercise-2: Matrix Addition

As the next exercise, add two matrices. Below is the logic. User gives the matrix dimensions, and also the matrix elements. 

```
Enter the matrix range: Enter one value
                        Enter another value
The entered the range is: print the NxM
Enter the values for your first matrix: Enter the 1st value
                                        Enter the 2nd value
                                        Enter the 3rd value
                                        Enter the 4th value
                                        Enter the 5th value
                                        Enter the 6th value
Your matrix is: print it like a matrix, not like a list
Enter the values for your second matrix: Enter the 1st value
                                        Enter the 2nd value
                                        Enter the 3rd value
                                        Enter the 4th value
                                        Enter the 5th value
                                        Enter the 6th value
Your matrix is: print it like a matrix, not like a list
Print Matrix1 + Matrix2 = Output Matrix (print them like matrices, not lists)
```

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print a
b = np.array([[1,2,3],[4,5,6]])
print b

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [14]:
# Somehow, this one was a bit easier than the first exercise. This is done!

print "Matrix Addition\n==============="
print "We need a few things from you. \nYou will give us the dimensions as well as the values for both matrices.\n"
#---------------------------------------------------------------#
print "Matrix-1:\n---------"

rows1 = input("How many rows you would like in your first matrix? ")
cols1 = input("How many columns you would like in your first matrix? ")
values1 = rows1 * cols1
print "The matrix you have chosen is, ", rows1, "x", cols1, "matrix with ", rows1, "rows and ", cols1, "columns, and totally ", values1, "elements inside the matrix."
list1 = []
for i in range(values1):
    x = input("Enter your Value-")
    print "This is your Value-", i
    list1.append(x)

matrix1 = np.asarray(list1)
matrix1 = matrix1.reshape(rows1, cols1)
print "This is your first matrix: \n", matrix1
#---------------------------------------------------------------#
print "Matrix-2:\n---------"

rows2 = input("How many rows you would like in your second matrix? ")
cols2 = input("How many columns you would like in your second matrix? ")
values2 = rows2 * cols2
print "The matrix you have chosen is, ", rows2, "x", cols2, "matrix with ", rows2, "rows and ", cols2, "columns, and totally ", values2, "elements inside the matrix."
list2 = []
for i in range(values2):
    x = input("Enter your Value-")
    print "This is your Value-", i
    list2.append(x)

matrix2 = np.asarray(list2)
matrix2 = matrix2.reshape(rows2, cols2)
print "This is your second matrix: \n", matrix2
#---------------------------------------------------------------#
print "Adding your matrices ...\n------------------------"
resultant = matrix1 + matrix2
print "Matrix-1 \n", matrix1, "\n+ \nMatrix-2 \n", matrix2, "\n= \nResultant Matrix \n", resultant

Matrix Addition
We need a few things from you. 
You will give us the dimensions as well as the values for both matrices.

Matrix-1:
---------
How many rows you would like in your first matrix? 2
How many columns you would like in your first matrix? 2
The matrix you have chosen is,  2 x 2 matrix with  2 rows and  2 columns, and totally  4 elements inside the matrix.
Enter your Value-1
This is your Value- 0
Enter your Value-4
This is your Value- 1
Enter your Value-8
This is your Value- 2
Enter your Value-2
This is your Value- 3
This is your first matrix:  [[1 4]
 [8 2]]
Matrix-2:
---------
How many rows you would like in your second matrix? 2
How many columns you would like in your second matrix? 2
The matrix you have chosen is,  2 x 2 matrix with  2 rows and  2 columns, and totally  4 elements inside the matrix.
Enter your Value-3
This is your Value- 0
Enter your Value-5
This is your Value- 1
Enter your Value-9
This is your Value- 2
Enter your Value-8
This is your Value- 3
This is your 